create table "public"."testTable" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."testTable" enable row level security;

CREATE UNIQUE INDEX "testTable_pkey" ON public."testTable" USING btree (id);

alter table "public"."testTable" add constraint "testTable_pkey" PRIMARY KEY using index "testTable_pkey";

grant delete on table "public"."testTable" to "anon";

grant insert on table "public"."testTable" to "anon";

grant references on table "public"."testTable" to "anon";

grant select on table "public"."testTable" to "anon";

grant trigger on table "public"."testTable" to "anon";

grant truncate on table "public"."testTable" to "anon";

grant update on table "public"."testTable" to "anon";

grant delete on table "public"."testTable" to "authenticated";

grant insert on table "public"."testTable" to "authenticated";

grant references on table "public"."testTable" to "authenticated";

grant select on table "public"."testTable" to "authenticated";

grant trigger on table "public"."testTable" to "authenticated";

grant truncate on table "public"."testTable" to "authenticated";

grant update on table "public"."testTable" to "authenticated";

grant delete on table "public"."testTable" to "service_role";

grant insert on table "public"."testTable" to "service_role";

grant references on table "public"."testTable" to "service_role";

grant select on table "public"."testTable" to "service_role";

grant trigger on table "public"."testTable" to "service_role";

grant truncate on table "public"."testTable" to "service_role";

grant update on table "public"."testTable" to "service_role";


